defaults:
  - defaults.yaml
  - model: poyo_11.8M.yaml
  - dataset: poyo_1.yaml
  - _self_  # ensures current config overrides defaults

train_transforms:
  - _target_: torch_brain.transforms.UnitDropout
    max_units: 300
    min_units: 30
    mode_units: 100
    peak: 4

wandb:
  run_name: poyo_1
