defaults:
  - data_ssl: odoherty.yaml
  - data_superv: odoherty.yaml
  - _self_

subtask_idx: 2
data_root: ./data/process

ctx_time: 1.0
bin_time: 0.02
patch_size: [32, 1]
pad_val: 64
train_ratio: 0.8

model:
  dim: 256
  max_time_patches: 256
  max_space_patches: 256
  patchifier: {}
  encoder:
    depth: 6
    heads: 4
    dropout: 0.1
    ffn_mult: 1 
  predictor:
    depth: 2
    heads: 4
    dropout: 0.1
    ffn_mult: 1 
  bhv_decoder:
    depth: 2
    heads: 4
    dropout: 0.1
    ffn_mult: 1
    decode_time_pool: "mean"
    behavior_dim: 2
    behavior_lag: 1.2

    

mask_ratio: 0.5

fast_dev_run: false
num_sanity_val_steps: 0

seed: 0
split_seed: 0
batch_size: 512
superv_batch_size: null  # defaults to batch_size
epochs: 250
eval_epochs: 1

precision: bf16-mixed
num_workers: 8

optimizer:
  lr: 0.0005
  weight_decay: 0.01  
  start_factor: 0.1   #LinearLR
  warmup_steps: 100   #LinearLR
  decay_steps: 2500   # matched to NDT2 codebase
  lr_min: 1e-6        # matched to NDT2 codebase

log_dir: ./logs
log_every_n_steps: 10

wandb:
  enable: true
  entity: aandre8-gatech  # chooses default username
  project: reproduce_NDT2
  run_name: null

ssl_only: false
superv_only: true
encoder_finetune: false

checkpoint:
  enable: false
  every_n_steps: 1000
  every_n_epochs: null
  save_all: true