defaults:
  - _default
  - dataset: train.yaml
  - _self_


batch_size: 512
mask_ratio: 0.5
is_ssl: true
unsorted: true
keep_M1_units: true
train_ratio: 0.8

optimizer:
  scheduler: true
  lr: 0.0005
  weight_decay: 0.01  
  start_factor: 0.1  
  warmup_steps: 100   
  decay_steps: 2500   
  lr_min: 1e-6        

load_from_checkpoint: false

