- selection:
  - brainset: pei_pandarinath_nlb_2021
  config:
    multitask_readout:
      - readout_id: cursor_velocity_2d
        timestamp_key: hand.timestamps
        value_key: hand.vel
        normalize_mean: 0.
        normalize_std: 100.
        metrics:
        - metric:
            _target_: torchmetrics.R2Score
        eval_interval: nlb_eval_intervals
