_target_: torch_brain.models.POYOPlus
sequence_length: 0.5
sequence_start_threshold: 0.2
latent_step: 0.125
num_latents_per_step: 16
dim_enc: 64
dim_mid: 64
dim_dec: 64
dim_head: 64
depth: 6
cross_heads: 2
self_heads: 8
ffn_dropout: 0.2
lin_dropout: 0.4
atn_dropout: 0.2