# defaults used for training POYO+
# this file needs to be combined with a model config and a dataset config

# Paths
data_root: /home/ynffsy/Desktop/andersen_lab/data/neurogalaxy/processed
log_dir: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs

# Transforms
train_transforms: []
eval_transforms: []

# Training
epochs: 100
batch_size: 80
eval_epochs: 1
eval_batch_size: null  # if null, will use batch_size
seed: 42  # use to set random seed
sanity_check_validation: false  # if true, will start the run with validation 

optim:
  base_lr: 6.25e-6  # scaled linearly by batch size
  weight_decay: 1e-4
  lr_decay_start: 0.5  # fraction of epochs before starting LR decay

# Logging
wandb:
  enable: true
  entity: null
  project: poyo
  run_name: null
  log_model: false

# GPU and CPU
precision: 32
nodes: 1
gpus: 1
num_workers: 4

# Checkpointing
ckpt_path: null  # for resuming training, or loading a model during finetuning
