defaults:
  - defaults.yaml
  - model: poyo_single_session.yaml
  # - dataset: perich_miller_population_2018.yaml
  - dataset: ALMG103CO_OT_A0.yaml
  # - dataset: ALMG103CO_OT_AL0.35.yaml
  # - dataset: ALMG103CO_OT_AX.yaml
  # - dataset: ALMG103CO_OT_OL.yaml
  - _self_

train_transforms:
  - _target_: torch_brain.transforms.UnitDropout
    max_units: 1000
    min_units: 60
    mode_units: 300
    peak: 4

wandb:
  run_name: poyo_mp_mini_test

# ckpt_path: null  # Must specify path to model to finetune


# ALMGCO103 OT A0 N2
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/f3n49428/checkpoints/last.ckpt

# ALMGCO103 OT A0 N2 (excluding last 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/2dng1oon/checkpoints/last.ckpt

# ALMGCO103 OT A0 N2 (excluding first 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/vo7pzhet/checkpoints/last.ckpt

# ALMGCO103 OT AL0.35 N2
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/f28stwgn/checkpoints/last.ckpt

# ALMGCO103 OT AL0.35 N2 (excluding last 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/hka4expa/checkpoints/last.ckpt

# ALMGCO103 OT AL0.35 N2 (excluding first 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/fre7cbdl/checkpoints/last.ckpt


# ALMGCO103 OT A0 N1
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/atc8pmc2/checkpoints/last.ckpt

# ALMGCO103 OT A0 N1 (excluding last 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/wqrrb6yl/checkpoints/last.ckpt

# ALMGCO103 OT A0 N1 (excluding first 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/7i8wxcj1/checkpoints/last.ckpt

# ALMGCO103 OT AL0.35 N1
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo//checkpoints/last.ckpt

# ALMGCO103 OT AL0.35 N1 (excluding last 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/e7rx0ph9/checkpoints/last.ckpt

# ALMGCO103 OT AL0.35 N1 (excluding first 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/jcj6rjha/checkpoints/last.ckpt


# ALMGCO103 OT noCAR N2 (excluding last 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/wxwtc67p/checkpoints/last.ckpt

# ALMGCO103 OT noCAR N2 (excluding last 3) -> finetune on ALMGCO103 OT OL N2 (last 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/gmxi5516/checkpoints/last.ckpt

# ALMGCO103 OT noCAR N2 (excluding last 3) -> finetune on ALMGCO103 OT OL N2 (first one of last 3)
# ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/6os0p93w/checkpoints/last.ckpt

# ALMGCO103 OT noCAR N2 (excluding last 3) -> finetune on ALMGCO103 OT AX N2 (last 3)
ckpt_path: /home/ynffsy/Desktop/andersen_lab/results/neurogalaxy/logs/poyo/o5c7hq7l/checkpoints/last.ckpt





